//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceWare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceWare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111	0	
        ///11112	1	
        ///11113	2	
        ///11114	3	
        ///11115	4	
        ///11116	5	
        ///11121	6	
        ///11122	7	
        ///11123	8	
        ///11124	9	
        ///11125	10	
        ///11126	11	
        ///11131	12	
        ///11132	13	
        ///11133	14	
        ///11134	15	
        ///11135	16	
        ///11136	17	
        ///11141	18	
        ///11142	19	
        ///11143	20	
        ///11144	21	
        ///11145	22	
        ///11146	23	
        ///11151	24	
        ///11152	25	
        ///11153	26	
        ///11154	27	
        ///11155	28	
        ///11156	29	
        ///11161	30	
        ///11162	31	
        ///11163	32	
        ///11164	33	
        ///11165	34	
        ///11166	35	
        ///11211	36	
        ///11212	37	
        ///11213	38	
        ///11214	39	
        ///11215	40	
        ///11216	41	
        ///11221	42	
        ///11222	43	
        ///11223	44	
        ///11224	45	
        ///11225	46	
        ///11226	47	
        ///11231	48	
        ///11232	49	
        ///11233	50	
        ///11234	51	
        ///11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diceware {
            get {
                return ResourceManager.GetString("diceware", resourceCulture);
            }
        }
    }
}
